//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServiceLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class An
    {
        public An()
        {
            this.Vehiculs = new HashSet<Vehicul>();
        }
    
        public int AnID { get; set; }
        public short An1 { get; set; }
    
        public virtual ICollection<Vehicul> Vehiculs { get; set; }
    }
}
