//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServiceLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class MartoriBord
    {
        public MartoriBord()
        {
            this.ModRezolvares = new HashSet<ModRezolvare>();
        }
    
        public int MartorID { get; set; }
        public string Nume { get; set; }
        public string Descriere { get; set; }
        public string ModRezolvare { get; set; }
    
        public virtual ICollection<ModRezolvare> ModRezolvares { get; set; }
    }
}
