//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServiceLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModRezolvare
    {
        public int RezolvareID { get; set; }
        public string ModeRezolvare { get; set; }
        public Nullable<int> MartorID { get; set; }
    
        public virtual MartoriBord MartoriBord { get; set; }
    }
}
