//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServiceLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motorizare
    {
        public Motorizare()
        {
            this.Vehiculs = new HashSet<Vehicul>();
        }
    
        public int MotorizareID { get; set; }
        public string Nume { get; set; }
        public int ProducatorID { get; set; }
        public string An { get; set; }
    
        public virtual ICollection<Vehicul> Vehiculs { get; set; }
    }
}
