//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServiceLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicul
    {
        public int VehiculID { get; set; }
        public int ModelID { get; set; }
        public int MotorizareID { get; set; }
        public int An { get; set; }
    
        public virtual An An1 { get; set; }
        public virtual Model Model { get; set; }
        public virtual Motorizare Motorizare { get; set; }
    }
}
